" Remap jk to ESC
inoremap jk <ESC>

"let mapleader = "\<Space>"

filetype plugin indent on
syntax on
set encoding=utf-8

" To use system clipboard. Use unnamedplus in Linux
set clipboard=unnamed 

" Show line numbers
set number

" Vim-Plug(junegunn/vim-plug). Run the following on windows. Not checking this in because it needs to be updated.
" md ~\vimfiles\autoload
" $uri = 'https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
" (New-Object Net.WebClient).DownloadFile($uri, $ExecutionContext.SessionState.Path.GetUnresolvedProviderPathFromPSPath("~\vimfiles\autoload\plug.vim"))

" Specify a directory for plugins (for Neovim: ~/.local/share/nvim/plugged)
call plug#begin('~/_vim/plugged')

" NERDtree will be loaded on the first invocation of NERDTreeToggle command
Plug 'scrooloose/nerdtree', { 'on': 'NERDTreeToggle' }

" Initialize plugin system
call plug#end()

" Nerd Tree show
map <C-n> :NERDTreeToggle<CR>
