# Aliases
alias gs='git status'
alias ga='git add'
alias gf='git fetch'
alias gm='git merge'
alias gr='git rebase'
alias gc='git commit'
alias gco='git checkout'
alias gst='git stash'
alias gl='git lg'
alias gp='git push'
alias gd='git diff'
